version: '3.5'

services:

   todolist:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: todolist
     env_file:
       - .env.docker
     working_dir: /code
     volumes:
       - .:/code
     networks:
       - todolist-network
     ports:
       - 8080:80
       - 9080:9000

   todolist-db:
     image: mysql:5.7
     container_name: todolist-db
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=application
     networks:
       - todolist-network
     ports:
       - 3386:3306

networks:
   todolist-network:
     name: todolist-network
